database:
  init_script: "database/init_db.sql"
  URL: "/etc/Virus-Encoder-Detector/detector.db"

logger:
  all_logs: "/etc/Virus-Encoder-Detector/logs/detector_all.log"
  latest_readable: "/etc/Virus-Encoder-Detector/logs/detector_latest_readable.log"

